spring.application.name=demo
# Configuracion de la base de datos
spring.datasource.url=jdbc:h2:mem:yogurtdb;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.userName=sa
spring.datasource.password=


#Configuracion del JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
sprint.jpa.properties.hibernate.format_sql=true
spring.jpa.defer_datasource-initialization=true

#Configuracion de H2 y su consola
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Ajustes para el login
logging.level.com.yogurtmaker=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#Puerto de nuestra app
server.port=8082

#Inicializacion de SQL
spring.sql.init.mode=always
spring.sql.init.data.-location=classpath:data.sql